language: python
python:
  - "3.8"
addons:
  apt:
    packages:
    - x11-utils
    - libxkbcommon-x11-0
    - libxcb-randr0-dev
    - libxcb-xtest0-dev
    - libxcb-xinerama0-dev
    - libxcb-shape0-dev
    - libxcb-xkb-dev
    - libxcb-render-util0
    - libxcb-icccm4
    - libxcb-keysyms1
    - libxcb-image0
services: xvfb
install:
  - sudo apt-get update
  - "export PYTHONPATH=$PYTHONPATH:$(pwd)/src"
  - pip install cx-freeze
  - pip install -e .
  
script:
  - black --check *.py
  - python -m pytest -sv --cov=src tests/

after_success:
  - bash <(curl -s https://codecov.io/bash) -v
