name: Linting & Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry
        poetry install
        poetry add pylint-exit
    - name: Analysing the code with pylint
      run: |
        poetry run pylint --rcfile pyproject.toml joystick_diagrams/ tests/ || poetry run pylint-exit $?
    - name: Run tests
      run: poetry run pytest -m "not uitest" --cov-report=term-missing --cov=./  --cov-report=xml
    - name: Run Upload coverage
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}